// AUTO-GENERATED by @polymorph/adapter-kotlin — DO NOT EDIT.
// Source: contract version 0.0.0, mode "light".
// Regenerate by running the CLI's transform command or update-goldens script.
// Generated object: BorealisThemeLight.
package polymorph.theme

import androidx.compose.animation.core.CubicBezierEasing
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/**
 * Container for a Polymorph typography composite. Apply by constructing a Compose [TextStyle]:
 *   TextStyle(fontSize = style.fontSize, fontWeight = style.fontWeight, ...)
 */
data class PolymorphTextStyle(
  val fontFamily: String,
  val fontSize: TextUnit,
  val fontWeight: FontWeight,
  val lineHeight: Float,
  val letterSpacing: TextUnit,
)

/** Container for a Polymorph shadow. Apply via Modifier.shadow / drawBehind in Compose. */
data class PolymorphShadow(
  val color: Color,
  val x: Dp,
  val y: Dp,
  val radius: Dp,
)

/** Polymorph theme — generated from contract v0.0.0, mode "light". */
object BorealisThemeLight {

  // region Colors
  val colorSurfaceBase: Color = Color(0xFFFBF8F3)
  val colorSurfaceRaised: Color = Color(0xFFF3ECE0)
  val colorSurfaceSunken: Color = Color(0xFFF1EEE9)
  val colorSurfaceOverlay: Color = Color(0xFFF3ECE0)
  val colorSurfaceInverse: Color = Color(0xFF231B12)
  val colorTextBody: Color = Color(0xFF231B12)
  val colorTextMuted: Color = Color(0xFF6B5E4D)
  val colorTextSubtle: Color = Color(0xFF817668)
  val colorTextOnAction: Color = Color(0xFFFFFFFF)
  val colorTextOnInverse: Color = Color(0xFFFBF8F3)
  val colorTextLink: Color = Color(0xFF0F7A5A)
  val colorTextDisabled: Color = Color(0xFFA59C8F)
  val colorActionPrimaryRest: Color = Color(0xFF0F7A5A)
  val colorActionPrimaryHover: Color = Color(0xFF0E6E51)
  val colorActionPrimaryPressed: Color = Color(0xFF0C6248)
  val colorActionPrimaryDisabled: Color = Color(0xFF91BFAE)
  val colorActionSecondaryRest: Color = Color(0xFF7A6A52)
  val colorActionSecondaryPressed: Color = Color(0xFF625542)
  val colorActionDangerRest: Color = Color(0xFFB23030)
  val colorActionDangerPressed: Color = Color(0xFF8E2626)
  val colorFeedbackSuccess: Color = Color(0xFF2E8B4F)
  val colorFeedbackWarning: Color = Color(0xFFB3791F)
  val colorFeedbackError: Color = Color(0xFFB23030)
  val colorFeedbackInfo: Color = Color(0xFF2F6F8F)
  val colorBorderDefault: Color = Color(0xFFDDD0BD)
  val colorBorderSubtle: Color = Color(0xFFEBE3D7)
  val colorBorderStrong: Color = Color(0xFFB1A697)
  val colorBorderFocus: Color = Color(0xFF0F7A5A)
  // endregion

  // region Dimensions / spacing / radii / sizes
  val spaceNone: Dp = 0.0f.dp
  val spaceXs: Dp = 3.0f.dp
  val spaceSm: Dp = 6.0f.dp
  val spaceMd: Dp = 12.0f.dp
  val spaceLg: Dp = 18.0f.dp
  val spaceXl: Dp = 24.0f.dp
  val space2xl: Dp = 36.0f.dp
  val space3xl: Dp = 48.0f.dp
  val radiusNone: Dp = 0.0f.dp
  val radiusControl: Dp = 4.0f.dp
  val radiusCard: Dp = 6.0f.dp
  val radiusPill: Dp = 999.0f.dp
  val radiusFull: Dp = 9999.0f.dp
  val borderWidthHairline: Dp = 1.0f.dp
  val borderWidthThin: Dp = 1.5f.dp
  val borderWidthThick: Dp = 3.0f.dp
  val sizeControlSm: Dp = 36.0f.dp
  val sizeControlMd: Dp = 48.0f.dp
  val sizeControlLg: Dp = 56.0f.dp
  val sizeTouchTargetMin: Dp = 48.0f.dp
  val sizeIconMd: Dp = 24.0f.dp
  // endregion

  // region Numbers / opacities
  val opacityDisabled: Float = 0.4f
  val opacityMuted: Float = 0.6f
  val opacityScrim: Float = 0.5f
  // endregion

  // region Motion (durations + easings)
  val motionDurationShort: Int = 120
  val motionDurationBase: Int = 220
  val motionDurationLong: Int = 400
  val motionEasingStandard: CubicBezierEasing = CubicBezierEasing(0.4f, 0.0f, 0.2f, 1.0f)
  val motionEasingEmphasized: CubicBezierEasing = CubicBezierEasing(0.2f, 0.0f, 0.0f, 1.0f)
  // endregion

  // region Typography
  val typographyDisplay: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 36.0f.sp,
    fontWeight = FontWeight.W600,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyHeading: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 24.0f.sp,
    fontWeight = FontWeight.W600,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyHeadingSm: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 18.0f.sp,
    fontWeight = FontWeight.W600,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyBody: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 16.0f.sp,
    fontWeight = FontWeight.W400,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyBodyStrong: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 16.0f.sp,
    fontWeight = FontWeight.W600,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyLabel: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 14.0f.sp,
    fontWeight = FontWeight.W600,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyCaption: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 12.0f.sp,
    fontWeight = FontWeight.W400,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  val typographyMono: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 16.0f.sp,
    fontWeight = FontWeight.W400,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  // endregion

  // region Shadows
  val elevationFlat: List<PolymorphShadow> = listOf(
    PolymorphShadow(color = Color(0xFF000000), x = 0.0f.dp, y = 0.0f.dp, radius = 0.0f.dp),
  )
  val elevationRaised: List<PolymorphShadow> = listOf(
    PolymorphShadow(color = Color(0xFF000000), x = 0.0f.dp, y = 2.0f.dp, radius = 6.0f.dp),
  )
  val elevationOverlay: List<PolymorphShadow> = listOf(
    PolymorphShadow(color = Color(0xFF000000), x = 0.0f.dp, y = 8.0f.dp, radius = 24.0f.dp),
  )
  // endregion

  // region Component tokens (override resolved)
  val buttonPrimaryBackground: Color = Color(0xFF0F7A5A)
  val buttonPrimaryForeground: Color = Color(0xFFFFFFFF)
  val buttonPrimaryRadius: Dp = 4.0f.dp
  val buttonSecondaryBackground: Color = Color(0xFF7A6A52)
  val buttonSecondaryBorder: Color = Color(0xFF7A6A52)
  val buttonSecondaryForeground: Color = Color(0xFF231B12)
  val buttonDangerBackground: Color = Color(0xFFB23030)
  val buttonDangerForeground: Color = Color(0xFFFFFFFF)
  val inputBackground: Color = Color(0xFFF3ECE0)
  val inputBorder: Color = Color(0xFFDDD0BD)
  val inputBorderFocus: Color = Color(0xFF0F7A5A)
  val inputForeground: Color = Color(0xFF231B12)
  val inputRadius: Dp = 4.0f.dp
  val cardBackground: Color = Color(0xFFF3ECE0)
  val cardRadius: Dp = 6.0f.dp
  val cardElevation: List<PolymorphShadow> = listOf(
    PolymorphShadow(color = Color(0xFF000000), x = 0.0f.dp, y = 2.0f.dp, radius = 6.0f.dp),
  )
  val stepIndicatorActiveColor: Color = Color(0xFF0F7A5A)
  val stepIndicatorInactiveColor: Color = Color(0xFFDDD0BD)
  val disclosureForeground: Color = Color(0xFF6B5E4D)
  val disclosureTypography: PolymorphTextStyle = PolymorphTextStyle(
    fontFamily = "Georgia",
    fontSize = 12.0f.sp,
    fontWeight = FontWeight.W400,
    lineHeight = 1.4f,
    letterSpacing = 0.0f.sp,
  )
  // endregion
}
