// AUTO-GENERATED by @polymorph/adapter-flutter — DO NOT EDIT.
// Source: contract version 0.0.0, mode "light".
// Regenerate by running the CLI's transform command or update-goldens script.
// Generated class: AuroraThemeLight.
// ignore_for_file: constant_identifier_names, prefer_const_constructors
import 'package:flutter/material.dart';
import 'package:flutter/animation.dart';

/// Polymorph theme — generated from contract v0.0.0, mode "light".
class AuroraThemeLight {

  // ---- Colors ----------------------------------------------------------------
  static const Color colorSurfaceBase = Color(0xFFFFFFFF);
  static const Color colorSurfaceRaised = Color(0xFFF4F7FF);
  static const Color colorSurfaceSunken = Color(0xFFF5F5F5);
  static const Color colorSurfaceOverlay = Color(0xFFF4F7FF);
  static const Color colorSurfaceInverse = Color(0xFF0B1B2B);
  static const Color colorTextBody = Color(0xFF0B1B2B);
  static const Color colorTextMuted = Color(0xFF5A6B7B);
  static const Color colorTextSubtle = Color(0xFF73818F);
  static const Color colorTextOnAction = Color(0xFFFFFFFF);
  static const Color colorTextOnInverse = Color(0xFFFFFFFF);
  static const Color colorTextLink = Color(0xFF1F5CFF);
  static const Color colorTextDisabled = Color(0xFF9CA6B0);
  static const Color colorActionPrimaryRest = Color(0xFF1F5CFF);
  static const Color colorActionPrimaryHover = Color(0xFF1C53E6);
  static const Color colorActionPrimaryPressed = Color(0xFF194ACC);
  static const Color colorActionPrimaryDisabled = Color(0xFF9AB6FF);
  static const Color colorActionSecondaryRest = Color(0xFF5B6B7F);
  static const Color colorActionSecondaryPressed = Color(0xFF495666);
  static const Color colorActionDangerRest = Color(0xFFD23B3B);
  static const Color colorActionDangerPressed = Color(0xFFA82F2F);
  static const Color colorFeedbackSuccess = Color(0xFF1F9D57);
  static const Color colorFeedbackWarning = Color(0xFFC98A00);
  static const Color colorFeedbackError = Color(0xFFD23B3B);
  static const Color colorFeedbackInfo = Color(0xFF1F86C9);
  static const Color colorBorderDefault = Color(0xFFD6E0EE);
  static const Color colorBorderSubtle = Color(0xFFE6ECF5);
  static const Color colorBorderStrong = Color(0xFFABB3BE);
  static const Color colorBorderFocus = Color(0xFF1F5CFF);

  // ---- Dimensions / spacing / radii / sizes ----------------------------------
  static const double spaceNone = 0.0;
  static const double spaceXs = 4.0;
  static const double spaceSm = 8.0;
  static const double spaceMd = 16.0;
  static const double spaceLg = 24.0;
  static const double spaceXl = 32.0;
  static const double space2xl = 48.0;
  static const double space3xl = 64.0;
  static const double radiusNone = 0.0;
  static const double radiusControl = 10.0;
  static const double radiusCard = 16.0;
  static const double radiusPill = 999.0;
  static const double radiusFull = 9999.0;
  static const double borderWidthHairline = 1.0;
  static const double borderWidthThin = 1.5;
  static const double borderWidthThick = 3.0;
  static const double sizeControlSm = 36.0;
  static const double sizeControlMd = 48.0;
  static const double sizeControlLg = 56.0;
  static const double sizeTouchTargetMin = 48.0;
  static const double sizeIconMd = 24.0;

  // ---- Numbers / opacities ---------------------------------------------------
  static const double opacityDisabled = 0.4;
  static const double opacityMuted = 0.6;
  static const double opacityScrim = 0.5;

  // ---- Motion (durations + easings) ------------------------------------------
  static const Duration motionDurationShort = Duration(milliseconds: 120);
  static const Duration motionDurationBase = Duration(milliseconds: 220);
  static const Duration motionDurationLong = Duration(milliseconds: 400);
  static const Duration motionDurationReduced = Duration(milliseconds: 1);
  static const Cubic motionEasingStandard = Cubic(0.4, 0.0, 0.2, 1.0);
  static const Cubic motionEasingEmphasized = Cubic(0.2, 0.0, 0.0, 1.0);
  static const Cubic motionEasingReduced = Cubic(0.0, 0.0, 1.0, 1.0);

  // ---- Typography ------------------------------------------------------------
  static const TextStyle typographyDisplay = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
      fontSize: 36.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyHeading = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
      fontSize: 24.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyHeadingSm = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
      fontSize: 18.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyBody = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w400,
      fontSize: 16.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyBodyStrong = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
      fontSize: 16.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyLabel = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w600,
      fontSize: 14.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyCaption = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w400,
      fontSize: 12.0,
      height: 1.4,
      letterSpacing: 0.0,
    );
  static const TextStyle typographyMono = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w400,
      fontSize: 16.0,
      height: 1.4,
      letterSpacing: 0.0,
    );

  // ---- Shadows ---------------------------------------------------------------
  static const List<BoxShadow> elevationFlat = <BoxShadow>[
      BoxShadow(color: Color(0xFF000000), offset: Offset(0.0, 0.0), blurRadius: 0.0, spreadRadius: 0.0),
    ];
  static const List<BoxShadow> elevationRaised = <BoxShadow>[
      BoxShadow(color: Color(0xFF000000), offset: Offset(0.0, 2.0), blurRadius: 6.0, spreadRadius: 0.0),
    ];
  static const List<BoxShadow> elevationOverlay = <BoxShadow>[
      BoxShadow(color: Color(0xFF000000), offset: Offset(0.0, 8.0), blurRadius: 24.0, spreadRadius: 0.0),
    ];

  // ---- Component tokens (override resolved) ----------------------------------
  static const Color buttonPrimaryBackground = Color(0xFF1F5CFF);
  static const Color buttonPrimaryForeground = Color(0xFFFFFFFF);
  static const double buttonPrimaryRadius = 10.0;
  static const Color buttonSecondaryBackground = Color(0xFF5B6B7F);
  static const Color buttonSecondaryBorder = Color(0xFF5B6B7F);
  static const Color buttonSecondaryForeground = Color(0xFF0B1B2B);
  static const Color buttonDangerBackground = Color(0xFFD23B3B);
  static const Color buttonDangerForeground = Color(0xFFFFFFFF);
  static const Color inputBackground = Color(0xFFF4F7FF);
  static const Color inputBorder = Color(0xFFD6E0EE);
  static const Color inputBorderFocus = Color(0xFF1F5CFF);
  static const Color inputForeground = Color(0xFF0B1B2B);
  static const double inputRadius = 10.0;
  static const Color cardBackground = Color(0xFFF4F7FF);
  static const double cardRadius = 16.0;
  static const List<BoxShadow> cardElevation = <BoxShadow>[
      BoxShadow(color: Color(0xFF000000), offset: Offset(0.0, 2.0), blurRadius: 6.0, spreadRadius: 0.0),
    ];
  static const Color stepIndicatorActiveColor = Color(0xFF1F5CFF);
  static const Color stepIndicatorInactiveColor = Color(0xFFD6E0EE);
  static const Color disclosureForeground = Color(0xFF5A6B7B);
  static const TextStyle disclosureTypography = TextStyle(
      fontFamily: 'Inter',
      fontWeight: FontWeight.w400,
      fontSize: 12.0,
      height: 1.4,
      letterSpacing: 0.0,
    );

  /// Opinionated Material ThemeData starting point. Extend per app.
  static ThemeData buildThemeData() {
    return ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: colorSurfaceBase,
      canvasColor: colorSurfaceBase,
      cardColor: colorSurfaceRaised,
      dividerColor: colorBorderDefault,
      primaryColor: colorActionPrimaryRest,
      colorScheme: ColorScheme.light(
        primary: colorActionPrimaryRest,
        onPrimary: colorTextOnAction,
        secondary: colorActionSecondaryRest,
        error: colorActionDangerRest,
        surface: colorSurfaceBase,
      ),
      textTheme: TextTheme(
        headlineMedium: typographyHeading,
        bodyLarge: typographyBody,
        labelLarge: typographyLabel,
        bodySmall: typographyCaption,
      ),
    );
  }
}
