// AUTO-GENERATED by @polymorph/adapter-swift — DO NOT EDIT.
// Source: contract version 0.0.0, mode "light".
// Regenerate by running the CLI's transform command or update-goldens script.
// Generated enum: BorealisThemeLight.
import SwiftUI

/// Container for a Polymorph typography composite. Apply via a small SwiftUI extension:
///   Text("…").font(style.font).lineSpacing(style.lineHeight - 1.0).tracking(style.letterSpacing)
public struct PolymorphTextStyle {
  public let font: Font
  public let fontSize: CGFloat
  public let weight: Font.Weight
  public let lineHeight: CGFloat
  public let letterSpacing: CGFloat
  public init(font: Font, fontSize: CGFloat, weight: Font.Weight, lineHeight: CGFloat, letterSpacing: CGFloat) {
    self.font = font
    self.fontSize = fontSize
    self.weight = weight
    self.lineHeight = lineHeight
    self.letterSpacing = letterSpacing
  }
}

/// Container for a Polymorph shadow. Apply via .shadow(color: s.color, radius: s.radius, x: s.x, y: s.y).
public struct PolymorphShadow {
  public let color: Color
  public let x: CGFloat
  public let y: CGFloat
  public let radius: CGFloat
  public init(color: Color, x: CGFloat, y: CGFloat, radius: CGFloat) {
    self.color = color
    self.x = x
    self.y = y
    self.radius = radius
  }
}

/// Polymorph theme — generated from contract v0.0.0, mode "light".
public enum BorealisThemeLight {

  // MARK: - Colors
  public static let colorSurfaceBase: Color = Color(red: 0.9843, green: 0.9725, blue: 0.9529)
  public static let colorSurfaceRaised: Color = Color(red: 0.9529, green: 0.9255, blue: 0.8784)
  public static let colorSurfaceSunken: Color = Color(red: 0.9451, green: 0.9333, blue: 0.9137)
  public static let colorSurfaceOverlay: Color = Color(red: 0.9529, green: 0.9255, blue: 0.8784)
  public static let colorSurfaceInverse: Color = Color(red: 0.1373, green: 0.1059, blue: 0.0706)
  public static let colorTextBody: Color = Color(red: 0.1373, green: 0.1059, blue: 0.0706)
  public static let colorTextMuted: Color = Color(red: 0.4196, green: 0.3686, blue: 0.302)
  public static let colorTextSubtle: Color = Color(red: 0.5059, green: 0.4627, blue: 0.4078)
  public static let colorTextOnAction: Color = Color(red: 1, green: 1, blue: 1)
  public static let colorTextOnInverse: Color = Color(red: 0.9843, green: 0.9725, blue: 0.9529)
  public static let colorTextLink: Color = Color(red: 0.0588, green: 0.4784, blue: 0.3529)
  public static let colorTextDisabled: Color = Color(red: 0.6471, green: 0.6118, blue: 0.5608)
  public static let colorActionPrimaryRest: Color = Color(red: 0.0588, green: 0.4784, blue: 0.3529)
  public static let colorActionPrimaryHover: Color = Color(red: 0.0549, green: 0.4314, blue: 0.3176)
  public static let colorActionPrimaryPressed: Color = Color(red: 0.0471, green: 0.3843, blue: 0.2824)
  public static let colorActionPrimaryDisabled: Color = Color(red: 0.5686, green: 0.749, blue: 0.6824)
  public static let colorActionSecondaryRest: Color = Color(red: 0.4784, green: 0.4157, blue: 0.3216)
  public static let colorActionSecondaryPressed: Color = Color(red: 0.3843, green: 0.3333, blue: 0.2588)
  public static let colorActionDangerRest: Color = Color(red: 0.698, green: 0.1882, blue: 0.1882)
  public static let colorActionDangerPressed: Color = Color(red: 0.5569, green: 0.149, blue: 0.149)
  public static let colorFeedbackSuccess: Color = Color(red: 0.1804, green: 0.5451, blue: 0.3098)
  public static let colorFeedbackWarning: Color = Color(red: 0.702, green: 0.4745, blue: 0.1216)
  public static let colorFeedbackError: Color = Color(red: 0.698, green: 0.1882, blue: 0.1882)
  public static let colorFeedbackInfo: Color = Color(red: 0.1843, green: 0.4353, blue: 0.5608)
  public static let colorBorderDefault: Color = Color(red: 0.8667, green: 0.8157, blue: 0.7412)
  public static let colorBorderSubtle: Color = Color(red: 0.9216, green: 0.8902, blue: 0.8431)
  public static let colorBorderStrong: Color = Color(red: 0.6941, green: 0.651, blue: 0.5922)
  public static let colorBorderFocus: Color = Color(red: 0.0588, green: 0.4784, blue: 0.3529)

  // MARK: - Dimensions / spacing / radii / sizes
  public static let spaceNone: CGFloat = 0.0
  public static let spaceXs: CGFloat = 3.0
  public static let spaceSm: CGFloat = 6.0
  public static let spaceMd: CGFloat = 12.0
  public static let spaceLg: CGFloat = 18.0
  public static let spaceXl: CGFloat = 24.0
  public static let space2xl: CGFloat = 36.0
  public static let space3xl: CGFloat = 48.0
  public static let radiusNone: CGFloat = 0.0
  public static let radiusControl: CGFloat = 4.0
  public static let radiusCard: CGFloat = 6.0
  public static let radiusPill: CGFloat = 999.0
  public static let radiusFull: CGFloat = 9999.0
  public static let borderWidthHairline: CGFloat = 1.0
  public static let borderWidthThin: CGFloat = 1.5
  public static let borderWidthThick: CGFloat = 3.0
  public static let sizeControlSm: CGFloat = 36.0
  public static let sizeControlMd: CGFloat = 48.0
  public static let sizeControlLg: CGFloat = 56.0
  public static let sizeTouchTargetMin: CGFloat = 48.0
  public static let sizeIconMd: CGFloat = 24.0

  // MARK: - Numbers / opacities
  public static let opacityDisabled: Double = 0.4
  public static let opacityMuted: Double = 0.6
  public static let opacityScrim: Double = 0.5

  // MARK: - Motion (durations + easings)
  public static let motionDurationShort: TimeInterval = 0.12
  public static let motionDurationBase: TimeInterval = 0.22
  public static let motionDurationLong: TimeInterval = 0.4
  public static let motionEasingStandard: (Double, Double, Double, Double) = (0.4, 0.0, 0.2, 1.0)
  public static let motionEasingEmphasized: (Double, Double, Double, Double) = (0.2, 0.0, 0.0, 1.0)

  // MARK: - Typography
  public static let typographyDisplay: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 36.0),
      fontSize: 36.0,
      weight: .semibold,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyHeading: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 24.0),
      fontSize: 24.0,
      weight: .semibold,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyHeadingSm: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 18.0),
      fontSize: 18.0,
      weight: .semibold,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyBody: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 16.0),
      fontSize: 16.0,
      weight: .regular,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyBodyStrong: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 16.0),
      fontSize: 16.0,
      weight: .semibold,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyLabel: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 14.0),
      fontSize: 14.0,
      weight: .semibold,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyCaption: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 12.0),
      fontSize: 12.0,
      weight: .regular,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
  public static let typographyMono: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 16.0),
      fontSize: 16.0,
      weight: .regular,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )

  // MARK: - Shadows
  public static let elevationFlat: [PolymorphShadow] = [
      PolymorphShadow(color: Color(red: 0, green: 0, blue: 0), x: 0.0, y: 0.0, radius: 0.0),
    ]
  public static let elevationRaised: [PolymorphShadow] = [
      PolymorphShadow(color: Color(red: 0, green: 0, blue: 0), x: 0.0, y: 2.0, radius: 6.0),
    ]
  public static let elevationOverlay: [PolymorphShadow] = [
      PolymorphShadow(color: Color(red: 0, green: 0, blue: 0), x: 0.0, y: 8.0, radius: 24.0),
    ]

  // MARK: - Component tokens (override resolved)
  public static let buttonPrimaryBackground: Color = Color(red: 0.0588, green: 0.4784, blue: 0.3529)
  public static let buttonPrimaryForeground: Color = Color(red: 1, green: 1, blue: 1)
  public static let buttonPrimaryRadius: CGFloat = 4.0
  public static let buttonSecondaryBackground: Color = Color(red: 0.4784, green: 0.4157, blue: 0.3216)
  public static let buttonSecondaryBorder: Color = Color(red: 0.4784, green: 0.4157, blue: 0.3216)
  public static let buttonSecondaryForeground: Color = Color(red: 0.1373, green: 0.1059, blue: 0.0706)
  public static let buttonDangerBackground: Color = Color(red: 0.698, green: 0.1882, blue: 0.1882)
  public static let buttonDangerForeground: Color = Color(red: 1, green: 1, blue: 1)
  public static let inputBackground: Color = Color(red: 0.9529, green: 0.9255, blue: 0.8784)
  public static let inputBorder: Color = Color(red: 0.8667, green: 0.8157, blue: 0.7412)
  public static let inputBorderFocus: Color = Color(red: 0.0588, green: 0.4784, blue: 0.3529)
  public static let inputForeground: Color = Color(red: 0.1373, green: 0.1059, blue: 0.0706)
  public static let inputRadius: CGFloat = 4.0
  public static let cardBackground: Color = Color(red: 0.9529, green: 0.9255, blue: 0.8784)
  public static let cardRadius: CGFloat = 6.0
  public static let cardElevation: [PolymorphShadow] = [
      PolymorphShadow(color: Color(red: 0, green: 0, blue: 0), x: 0.0, y: 2.0, radius: 6.0),
    ]
  public static let stepIndicatorActiveColor: Color = Color(red: 0.0588, green: 0.4784, blue: 0.3529)
  public static let stepIndicatorInactiveColor: Color = Color(red: 0.8667, green: 0.8157, blue: 0.7412)
  public static let disclosureForeground: Color = Color(red: 0.4196, green: 0.3686, blue: 0.302)
  public static let disclosureTypography: PolymorphTextStyle = PolymorphTextStyle(
      font: Font.custom("Georgia", size: 12.0),
      fontSize: 12.0,
      weight: .regular,
      lineHeight: 1.4,
      letterSpacing: 0.0
    )
}
